## 附属名称
name: YubaTechnology

## 作者名称
author: Luoyangan

## CH介绍
description: Cosmichigh-tech

## 主类
main: me.luoyangan.yubatechnology.YubaTechnology

## 你可以更改为你的项目仓库地址，或者你的个人网站。你也可以移除此项目。
website: https://luoyangmc.rth1.xyz/

## 该值将在构建时被自动替换为pom.xml中定义的版本。
## 不要更改此项目。
version: ${project.version}

## 这是运行该附属所需的最低MC版本。
api-version: 1.13

## 指定 Slimefun 作为依赖项，必须
depend:
- Slimefun
